### ISSUE TITLE
Initialize measurement matrix A randomly

### ISSUE THREAD

**Issue by Unkrible** [iboing/ISTA-NAS#1]
Hello, I have read your paper on NeruaIPS2020 and the code recently, it is an interesting work and outperforms all existing methods.
Congratulations!
But I have a question about the random measurement matrix A (dictionary).
In both the paper and the code, A (base_A_[normal / reduce]) is initialized by sampling from the normal distribution.
However, in the traditional Sparse Coding, the dictionary A  is also the learning objective to minimize the reconstruction error.
By randomly initializing A and not being trainable, it might just project the sparse op selection $z$ into a dense vector space by encoding,  and recover the trainable A_[normal/reduce] to the sparse space by the over-complete A.
Why is the randomly initialized dictionary useful?

**Comment by iboing** [comment]
Hello, thanks for your attention. The "sparse coding"  in your sense is dictionary learning where the dictionary matrix is to optimize. But actually, our "sprase coding" refers to the mtehods of sparse recovery, such as the formulation of LASSO, where A is fixed.  
The matrix A just specifies and fixes a connection between the original and compressed spaces.  We just utilize this connection to perform the gradient-based search on the compressed space, but what the connection is does not matter.

**Comment by Unkrible** [comment]
Thank you for reply! The idea of mapping a sparse vector to a dense space and thus performing gradient-descent search is great.
My question is that from Eqn.8 it appears that the sparse z_j needs to be recovered by solving the LASSO z_j(b_j).  That is to say, the  quality of the dictionary A still has an impact on the search efficiency. An extreme case, where the random initialized dictionary vector is highly  similar or even the same for each cell, would lead to a poor quality of the LASSO solution.
Just a little detail of doubt.

**Comment by iboing** [comment]
Yes. In LASSO, the measurement matrix A is fixed but has a great impact on the solution quality. In our analysis, the matrix A needs to satisfy the RIP condition, see Proposition 1. But in implementation we see that just randomly initialized A works well, so we relax the rigorous RIP condition. But it does not mean that A can be jointly optimized with the search process because we still need to pre-specify a mapping by fixed A.

**Comment by Unkrible** [comment]
Thanks!
Your ideas have inspired me a lot and I hope to continue to follow your work. :)
